feat: Add support for computed_members_map variable
mineiros-io/terraform-google-pubsub-topic pull request #11
Opened 2022-06-22 14:47 UTC by zied-elouaer

2022-07-04 08:45 UTC, mariux requested changes

2022-07-07 17:22 UTC, mariux requested changes

2022-07-07 17:22 UTC, mariux commented on README.tfdoc.hcl
> +          default     = var.members
that is not true anymore... ;) 

i think it is required now?

2022-07-07 21:02 UTC, zied-elouaer commented on README.tfdoc.hcl
> +          default     = var.members
Nice catch :) Fixed.

2022-07-08 10:43 UTC, waxb reviewed
lgtm, waiting for @waxb to release https://github.com/mineiros-io/terraform-google-pubsub-subscription/commit/b0ac58b004dd25c57696561c7ea689e5625c6d28

2022-07-08 11:48 UTC, waxb approved these changes
lgtm

2022-07-08 18:40 UTC, mariux approved these changes
lgtm

2022-07-08 18:40 UTC, merged